global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dockerpress-monitor'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # cAdvisor - container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'docker'

  # MariaDB Exporter (if added)
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']
        labels:
          service: 'database'

  # Redis/KeyDB Exporter (if added)
  - job_name: 'keydb'
    static_configs:
      - targets: ['keydb-exporter:9121']
        labels:
          service: 'cache'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'webserver'
